#control flags
DOTRAIN: True       #train model from scratch
PREPLOT: False       #plot some images before running model
POSTPLOT: True       #plot accuracy and loss over time
LAYEROUTPLOT: False  #plot layer outputs

#workdir and inputfile
wdirname: 'train'     #working directory relative to script    
odirname: 'out'      #output directory relative to script

#location of checkpoint to pre-load 
#manually set for now
#cptoload='/home/lachlan/CODEBASE/Patch_camelyon/train/220910_vacc77/cp-0044.ckpt'
cptoload: '/home/lachlan/CODEBASE/Patch_camelyon/train/220911_vacc75_c2d64/cp-0032.ckpt'

#data and model handling
batchlen: 1024    #size of batch for fitting
buffer: 10000       #buffer for shuffling
nepochs: 100       #no. epochs
stoplim: 3        #patience for early stop
savesteps: 257     #save checkpoint every X steps

#hyperparams
lamda: 0.0001      #regularisation param